//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class AtkinsMandrykModel : Model
{
	private byte[][] sensorsStates
	{
		get;
		set;
	}

	private byte[][] valenceArousalStates
	{
		get;
		set;
	}

	public AtkinsMandrykModel(Bitalino.Frame[] frames, double intervalle)
	{
	}

	private void DataToSensors()
	{
		throw new System.NotImplementedException();
	}

	private void SensorsToValenceArousal()
	{
		throw new System.NotImplementedException();
	}

}

