//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DataWriter
{
	private string path
	{
		get;
		set;
	}

	public virtual LiveSequencer liveSequencer
	{
		get;
		set;
	}

	public DataWriter()
	{
	}

	public virtual void OpenFile()
	{
		throw new System.NotImplementedException();
	}

	public virtual void WriteFile(string[] statesNames, byte[][] timedStates)
	{
		throw new System.NotImplementedException();
	}

	public virtual void CloseFile()
	{
		throw new System.NotImplementedException();
	}

}

