//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class LiveSequencer
{
	public DateTime startTimer
	{
		get;
		set;
	}

	public DateTime endTimer
	{
		get;
		set;
	}

	public string nomenclature
	{
		get;
		set;
	}

	public double timeInterval
	{
		get;
		set;
	}

	public int modelChosen
	{
		get;
		set;
	}

    /// <summary>
    /// A assigner lors de la creation du bitalino
    /// </summary>
	public Bitalino bitalino
	{
		get;
		set;
	}

    /// <summary>
    /// A assigner lors de la creation du model
    /// </summary>
	public Model Model
	{
		get;
		set;
	}

    /// <summary>
    /// A assigner lors de la creation du datawriter
    /// </summary>
	public virtual DataWriter dataWriter
	{
		get;
		set;
	}

	public MainForm.MainForm mainForm
	{
		get;
		set;
	}

	public LiveSequencer(string nomenclature, double interval, int idmodel, MainForm.MainForm mainForm)
	{
	}

	public void EndSession()
	{
		throw new System.NotImplementedException();
	}

	public void StartSession()
	{
		throw new System.NotImplementedException();
	}

}

