//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DataWriter
{
	public virtual string path
	{
		get;
		set;
	}

	public virtual LiveSequencer liveSequencer
	{
		get;
		set;
	}

	public DataWriter(string nomenclature, double) timeInterval)
	{
	}

	public virtual void OpenFile()
	{
		throw new System.NotImplementedException();
	}

	public virtual void WriteData(byte[][] timedStates, string[] statesNames)
	{
		throw new System.NotImplementedException();
	}

	public virtual void CloseFile()
	{
		throw new System.NotImplementedException();
	}

}

