//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class MainForm
{
	private bool isPaused
	{
		get;
		set;
	}

	private bool isAcquiring
	{
		get;
		set;
	}

	public virtual LiveSequencer liveSequencer
	{
		get;
		set;
	}

	public MainForm()
	{
	}

	public virtual void Pause()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Stop()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Start()
	{
		throw new System.NotImplementedException();
	}

}

