//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Model
{
	protected virtual Frame[] framesArray
	{
		get;
		set;
	}

	protected virtual short[][] dataArray
	{
		get;
		set;
	}

	public virtual byte idModel
	{
		get;
		set;
	}

	public virtual LiveSequencer liveSequencer
	{
		get;
		set;
	}

	public virtual string[] StatesNames()
	{
		throw new System.NotImplementedException();
	}

	public virtual byte[][] TimedStates()
	{
		throw new System.NotImplementedException();
	}

	protected virtual void FramesToData()
	{
		throw new System.NotImplementedException();
	}

}

